# Generated by Django 6.0.6 on 2026-06-21 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Профиль создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Профиль обновлен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Профиль создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Профиль обновлен'),
            preserve_default=False,
        ),
    ]
