# Generated by Django 6.0.6 on 2026-06-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Профиль обновлен'),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Профиль обновлен'),
        ),
    ]
